version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1 
  
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build 
          command: dotnet build
      - run: 
          name: Test
          command: dotnet test --no-build --logger "trx"
      - run:
          name: Publish test results
          when: always
          command: |
            dotnet tool install -g trx2junit
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> "$BASH_ENV"
            trx2junit tests/**/TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
      - store_artifacts:
          path: tests/TestResults
          destination: TestResults
    

  deploy:
    machine: # executor type
      image: ubuntu-1604:201903-01 

    steps:
      - checkout
      - azure-acr/build-and-push-image:
          login-server-name: regrubdevopsshowcase.azurecr.io
          registry-name: regrubdevopsshowcase
          repo: rub-devops-showcase
          tag: latest
      - run:
          name: Configure App Service
          command: >-
            az webapp config container set --name app-rub-devops-showcase 
            --resource-group rg-devops-showcase 
            --docker-custom-image-name regrubdevopsshowcase.azurecr.io/rub-devops-showcase:latest 
            --docker-registry-server-url https://regrubdevopsshowcase.azurecr.io

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master