version: 2.1

orbs:
  win: circleci/windows@2.2.0
  azure-acr: circleci/azure-acr@0.2.0

jobs:
  build:
    executor: win/default     
  
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build 
          command: dotnet build
      - run: 
          name: Test
          command: dotnet test

  deploy:
    machine: # executor type
      image: ubuntu-1604:201903-01 

    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: echo "Building Docker image"
      - azure-acr/build-and-push-image:
          login-server-name: regrubdevopsshowcase.azurecr.io
          registry-name: regrubdevopsshowcase
          repo: rub-devops-showcase
          tag: latest

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build